name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: setup android-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
        add-to-path: true
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Dosbox-Android
      run: |
          pushd app/src/main/jni
          ndk-build
          popd
          cd app
          ../gradlew
